### ISSUE TITLE
where  can I get data file  NIFTY50.csv

### ISSUE THREAD

**Issue by HubFire** [deependersingla/deep_trader#10]
where  can I get data file  NIFTY50.csv

**Comment by deependersingla** [comment]
Is it required anywhere? For running repo this is required:
a) cd tensor-reinforcement 
b) Copy data from https://drive.google.com/file/d/0B6ZrYxEMNGR-MEd5Ti0tTEJjMTQ/view into tensor-reinforcement directory and https://drive.google.com/file/d/0B6ZrYxEMNGR-Q0YwWWVpVnJ3YmM/view?usp=sharing.
