### ISSUE TITLE
code run error

### ISSUE THREAD

**Issue by tubu** [deependersingla/deep_trader#12]
I copy data from https://drive.google.com/file/d/0B6ZrYxEMNGR-MEd5Ti0tTEJjMTQ/view and https://drive.google.com/file/d/0B6ZrYxEMNGR-Q0YwWWVpVnJ3YmM/view?usp=sharing into tensor-reinforcement directory.

and run python dqn_model.py and get error:

Traceback (most recent call last):
  File "/Users/Wilson/github/deep_trader/tensor-reinforcement/dqn_model.py", line 12, in <module>
    from train_stock import *
  File "/Users/Wilson/github/deep_trader/tensor-reinforcement/train_stock.py", line 23, in <module>
    supervised_y_data  = episodic_data.make_supervised_data(data, data_dict)
  File "/Users/Wilson/github/deep_trader/tensor-reinforcement/episodic_data.py", line 100, in make_supervised_data
    supervised_data.append(episode_supervised_data(episode, data_dict))
  File "/Users/Wilson/github/deep_trader/tensor-reinforcement/episodic_data.py", line 86, in episode_supervised_data
    prices.append(data_average_price(data_dict, iteration))
  File "/Users/Wilson/github/deep_trader/tensor-reinforcement/episodic_data.py", line 92, in data_average_price
    data =  data_dict[key]
KeyError: '297956b2300474fda50a2a6b1d41a714'

**Comment by tubu** [comment]
I find some people get the sample error,but issue has been closed.

**Comment by deependersingla** [comment]
Hello @tubu ,

I will look into this over the weekend.

**Comment by tubu** [comment]
very good，thank you deependersingla!

**Comment by tubu** [comment]
hi，@deependersingla
   Has the problem been solved？

**Comment by deependersingla** [comment]
Hello @tubu 
I just followed instruction and its working for me. Are you copying data into tensor-reinforcement?

**Comment by tubu** [comment]
Yes,I copy data from https://drive.google.com/file/d/0B6ZrYxEMNGR-MEd5Ti0tTEJjMTQ/view and https://drive.google.com/file/d/0B6ZrYxEMNGR-Q0YwWWVpVnJ3YmM/view?usp=sharing into tensor-reinforcement directory. @deependersingla

**Comment by tubu** [comment]
I guess,the error log means hashcode dont match.Should be other key,but not '297956b2300474fda50a2a6b1d41a714'.
It can find the data.pkl and data_dict.pkl file and read data from them.@deependersingla

**Comment by deependersingla** [comment]
Maybe some version issue. I can't help you more than this. I will say see
the code, learn how it works and then try to replicate on some other assets
which you want to trade

**Comment by tubu** [comment]
ok，thank you！

**Comment by deependersingla** [comment]
@tubu also I am working on closed source version from a year now. To make RL work on stocks, input requires some great effort on feature engineering.
