### ISSUE TITLE
DQN Strategy

### ISSUE THREAD

**Issue by codnoob** [deependersingla/deep_trader#13]
I run the code as directed and get this error which I am not able to work through. Please help me with this.
Thanks

C:\Users\Aakash Juneja\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Traceback (most recent call last):
  File "dqn_model.py", line 8, in <module>
    from train_stock import *
  File "C:\Study Project (CEERI)\tensor_RL\train_stock.py", line 21, in <module>
    data = episodic_data.load_data("data.pkl",episode=10)
  File "C:\Study Project (CEERI)\tensor_RL\episodic_data.py", line 71, in load_data
    data = load_file_data(file)
  File "C:\Study Project (CEERI)\tensor_RL\episodic_data.py", line 76, in load_file_data
    data = six.moves.cPickle.load(myFile)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x97 in position 0: ordinal not in range(128)

**Comment by deependersingla** [comment]
Looks like some mismatch in your library versions. I am using python 2.7.
