### ISSUE TITLE
Do you want to calculate high + low / 2 for average price?

### ISSUE THREAD

**Issue by aaronzhudp** [deependersingla/deep_trader#4]
episodic_data.py#L39
temp = [data[2], data[3], data[4], data[5],data[8]]

episodic_data.py#L56
average_price = sum(temp[0:-2]) / float(len(temp[0:-2])) # (high + low + close ) /3 ?

Do you want to calculate high + low / 2 for average price? If yes, maybe line56 of episodic_data.py should be changed to as below...
average_price = sum(temp[1:-3]) / float(len(temp[1:-3])) 

Right?
 
![image](https://cloud.githubusercontent.com/assets/19245730/17460052/51aa1dde-5c87-11e6-8657-ac0be310345e.png)

**Comment by deependersingla** [comment]
@aaronzhudp the csv for the data has different column as compared to one on csv folder. Here is the link: https://drive.google.com/file/d/0B6ZrYxEMNGR-ZmNOUlBJeVpYZTQ/view?usp=sharing

I am taking average price (low + high + open + close)/4
